version: "3.8"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db_schedule
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_schedule
      MYSQL_USER: user_crud
      MYSQL_PASSWORD: root
      TZ: "America/Santiago"
    volumes:
      - ./mysql_schedule:/var/lib/mysql_schedule
    ports:
      - "3308:3306"